### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by pythoncode4day** [CCob/okta-terrify#6]
I get the following error after building executables: 
OktaTerrify.exe with db key and sid 
Can someone tell me how to fix it? 

.\OktaTerrify.exe --info --db "DataStore.db" --dbkey 3c210xx228200f563e8f9e86dc6854ce20bcb9714ec914bdXXXX24f30777cfae3ff --sid S-1-12-1-883658923-122XXX-XXX-XXXXXXX

Unhandled Exception: System.TypeInitializationException: The type initializer for 'SQLite.SQLiteConnection' threw an exception. ---> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at SQLitePCL.NativeLibrary.MakePossibilitiesFor(String basename, Assembly assy, Int32 flags, LibSuffix suffix)
   at SQLitePCL.NativeLibrary.MyLoad(String basename, Assembly assy, Int32 flags, Action`1 log)
   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at SQLite.SQLiteConnection..cctor()
   --- End of inner exception stack trace ---
   at SQLite.SQLiteConnection..ctor(SQLiteConnectionString connectionString)
   at OktaVerify.OktaTerrify.GetDatabaseInfo(String sid, String databasePath, Byte[] dbKey)
   at OktaVerify.OktaTerrify.<Main>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OktaVerify.OktaTerrify.<Main>(String[] args)

**Comment by CCob** [comment]
Is the runtimes folder in the output directory?

**Comment by pythoncode4day** [comment]
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at OktaVerify.OktaTerrify.GetDatabaseInfo(String sid, String databasePath, Byte[] dbKey)
   at OktaVerify.OktaTerrify.<Main>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OktaVerify.OktaTerrify.<Main>(String[] args)
